### PR TITLE
1-Day SIMM

### PR DESCRIPTION
**Pull request by srgcibc**
This PR adds the ability to calculate IM with a 1-day horizon. All top-level methods such as calculateStandard, calculateAdditional and calculateTotal have now got an additional parameter called holdingPeriod that can be either TenDay or OneDay.

@colinmyles

### CODE REVIEW

**Comment by srgcibc** [comment]
Successful build: https://ci.appveyor.com/project/srgcibc/simm-lib/builds/25699602

**Comment by srgcibc** [comment]
Successful build: https://ci.appveyor.com/project/srgcibc/simm-lib/builds/26408868

**Comment by AmitGee** [comment]
@Alec-Stewart can you please confirm if this PR was merged in ? I don't see anything pertaining to 1-day SIMM in the new 2.2 version but maybe I'm missing something. Thanks!

**Comment by AmitGee** [comment]
Ok thank you!

**Comment by AmitGee** [comment]
@Alec-Stewart Just want to check if the 1-day changes are imminent ? If you expect this to take long we are considering making the change ourselves and submitting a PR for you to merge, would that work for you? Thanks

**Comment by Alec-Stewart** [comment]
This change has been pulled in as of 2.2.1 - I made some changes to how it was implemented - namely going through and creating a 'config' class which should hold config parameters going forward - but the overall functionality has been kept and the library is passing the unit tests for 1-Day calculations. I am closing this issue with this update.

**Pull request closed without merging**
